package ru.vasadm.goodsList.data.list;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.DocumentReference;
import ru.vasadm.goodsList.data.product.ProductEntity;

import java.util.List;

@Document(collection = "Lists")
@Getter
@Setter
@ApiModel(description = "data model of list entity")
public class ListEntity {
    @Id
    @ApiModelProperty(value = "list id generated by db",position = 1)
    private String id;

    @ApiModelProperty(value = "list name",position = 2)
    private String name;

    public ListEntity(String name) {
        this.name = name;
    }

    @DocumentReference
    @ApiModelProperty(value = "products in the list",position = 3)
    private List<ProductEntity> products;
}
